### ISSUE TITLE
Support for Redmine 3.x?

### ISSUE THREAD

**Issue by dgutkowsky** [batizhevsky/redmine_pretend#12]
any chance for that?

**Comment by leonko** [comment]
I think it not hard to make support of rails 4/redmine 3. But I haven't been developing redmine plugins for years

**Comment by dgutkowsky** [comment]
thank you for the answer!

**Comment by cheoAlejo** [comment]
A must have plugin, very useful. It'd be great to have it on redmine 3.2

**Comment by leonko** [comment]
Guys have you had error "Your session has expired. Please login again."? Or another

**Comment by leonko** [comment]
I update plugin for support 3.2 and drop support 0.x and 1.x versions. Also I test this plugin only with 3.2. 
Please test carefully!

**Comment by nanego** [comment]
Thank you for this update. It looks great.

**Comment by nanego** [comment]
The error message "Your session has expired. Please login again." was the one I got since Redmine 3.2.0.

**Comment by itagent** [comment]
Same problem here
Redmine version                3.2.0.stable
Ruby version                   2.2.1-p85 (2015-02-26) [i686-linux]
Rails version                  4.2.5.1

**Comment by itagent** [comment]
@nanego check your .git/config if this the the project u use. I had the same error, but discovered, that I used a different fork

**Comment by nanego** [comment]
Yes, this bug has been fixed with the latest commits.

**Comment by batizhevsky** [comment]
That's great
