### ISSUE TITLE
Plugin throws expecption when requesting user pages (redmine 3.2)

### ISSUE THREAD

**Issue by itagent** [batizhevsky/redmine_pretend#15]
```
ActionView::Template::Error (undefined method `can_user_pretend_to?' for #<#<Class:0xb309a98>:0xb2da3b0>):
    1: <%= link_to l(:button_pretend), pretend_to_path(@user), :class => 'icon', :method => :post if can_user_pretend_to?(@user)  %>
  plugins/redmine_pretend/app/views/user/_pretend_to.html.erb:1:in `_4d7692822cb573ad1105219775cfaf5e'
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  plugins/redmine_git_hosting/app/views/users/show.html.erb:32:in `_5c0f1db739ffc3973ce5e6cf2b554e83'
  app/controllers/users_controller.rb:77:in `block (2 levels) in show'
  app/controllers/users_controller.rb:73:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

**Comment by batizhevsky** [comment]
Hello. Thank you for reporting the problem. Are you sure that you use the latest version of the plugin? Is this happened in production only, or in development too?

**Comment by itagent** [comment]
Sorry, but the issue is still there (Redmine 3.2 and checkout of master branch)

An ActionView::Template::Error occurred in users#show:

  undefined method `can_user_pretend_to?' for #<#<Class:0x117eb9ac>:0x117e9210>
  plugins/redmine_pretend/app/views/user/_pretend_to.html.erb:1:in `_72573c92a898617ffe4b2f9152e58198'

**Comment by topkool** [comment]
Same issue with same Redmine 3.2 version in production

**Comment by dimvic** [comment]
+1 for this issue

```
ActionView::Template::Error (undefined method `can_user_pretend_to?' for #<#<Class:0x0055e2ad99f8f0>:0x0055e2ace7e610>):
    1: <%= link_to l(:button_pretend), pretend_to_path(@user), :class => 'icon', :method => :post if can_user_pretend_to?(@user)  %>
  plugins/redmine_pretend/app/views/user/_pretend_to.html.erb:1:in `_plugins_redmine_pretend_app_views_user__pretend_to_html_erb___1258404009884212833_69890486957860'
```

**Comment by batizhevsky** [comment]
Sorry, guys, for the long delay.  I've pushed the fix to master. I thought it should solve the problem. Let me know if it helps.

**Comment by dimvic** [comment]
That did it for me in Redmine 3.2.1. Thank you very much!

**Comment by caranf** [comment]
Same issue with Redmine 3.2.2 production.
I have the latest version [(#65b69fa)](https://github.com/batizhevsky/redmine_pretend/commit/65b69fa9773fe5c5748556abf7378a66c97364ce)

Plugin throws exception: 

`ActionView::Template::Error (undefined method `can_user_pretend_to?' for #<#<Class:0x00000005d1b6e0>:0x007fdafdf9e090>):
    1: <%= link_to l(:button_pretend), pretend_to_path(@user), :class => 'icon', :method => :post if can_user_pretend_to?(@user)  %>
  plugins/redmine_pretend/app/views/user/_pretend_to.html.erb:1:in `_plugins_redmine_pretend_app_views_user__pretend_to_html_erb___2943843074760374847_70289270796980'`

**Comment by neoscopio** [comment]
+1

**Comment by batizhevsky** [comment]
@caranf the latest commit is #9da2ad3 
Please try to update and let me know about result

**Comment by neoscopio** [comment]
By the way, tag 1.0 is working.

**Comment by radist** [comment]
`I, [2017-04-09T14:25:19.926934 #25205]  INFO -- :   Rendered plugins/redmine_pretend/app/views/user/_pretend_to.html.erb (1186.4ms)
I, [2017-04-09T14:25:19.927339 #25205]  INFO -- :   Rendered users/show.html.erb within layouts/base (1402.4ms)
I, [2017-04-09T14:25:19.928539 #25205]  INFO -- : Completed 500 Internal Server Error in 1924ms (ActiveRecord: 252.2ms)
F, [2017-04-09T14:25:19.933602 #25205] FATAL -- : 
ActionView::Template::Error (undefined method `can_user_pretend_to?' for #<#<Class:0x00000009873d78>:0x007fdc587245e8>):
    1: <%= link_to(l(:button_pretend), pretend_to_path(@user), :class => 'icon', :method => :post) if can_user_pretend_to?(@user)  %>
  plugins/redmine_pretend/app/views/user/_pretend_to.html.erb:1:in `_959a2ce6465842aa728731ddaf7366b6'
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/users/show.html.erb:45:in `_09f4443a3fc213060c1563ba7625219d'
  app/controllers/users_controller.rb:77:in `block (2 levels) in show'
  app/controllers/users_controller.rb:73:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'`

`Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               PostgreSQL`
