### ISSUE TITLE
Internal Server Error 500 when displaying pretended user issues

### ISSUE THREAD

**Issue by esavard** [batizhevsky/redmine_pretend#18]
I installed the plugin from the master branch on Redmine 3.2.3 and I hit an error 500 when I visit issues for a _pretended user_.  Here is the error message from the production.log:

```
Completed 500 Internal Server Error in 449ms (ActiveRecord: 84.1ms)

ActionView::Template::Error (undefined local variable or method `current_unpretended_user' for #<#<Class:0x007fb3fe7ef090>:0x007fb3feeccef8>):
    1: <% if session[:real_user_id] %>
    2:   <div class="flash error">
    3:     <%= l(:pretend_message) %> <%= current_unpretended_user %>
    4:     <%= link_to l(:button_unpretend), unpretend_path, :class => 'icon', :method => :post %>
    5:   </div>
    6: <% end %>
  plugins/redmine_pretend/app/views/user/_unpretend.html.erb:3:in `_plugins_redmine_pretend_app_views_user__unpretend_html_erb___3850556622216845993_70205504753980'
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/layouts/base.html.erb:16:in `_app_views_layouts_base_html_erb___813464665339772456_70205504589380'
  app/controllers/issues_controller.rb:118:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:115:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Thanks.

**Comment by batizhevsky** [comment]
I've pushed fix. It might work)

**Comment by esavard** [comment]
With the latest commit, Redmine don't start and I have this line in Apache error_log:

> App 31325 stdout:

Thanks.

**Comment by batizhevsky** [comment]
Thank you. I will try to investigate how to fix this issue in the next few days. I could recommend disable plugin until it be fixed

**Comment by batizhevsky** [comment]
I rewrite loading of the plugin. I think it must help.

**Comment by radist** [comment]
`Started GET "/users/38" for 95.174.100.253 at 2016-06-24 23:07:28 +0300
Processing by UsersController#show as HTML
  Parameters: {"id"=>"38"}
  Current user: assmay (id=38)
  Rendered plugins/redmine_pretend/app/views/user/_pretend_to.html.erb (0.2ms)
  Rendered users/show.html.erb within layouts/base (62.5ms)
  Rendered inline template (0.7ms)
  Rendered inline template (0.6ms)
  Rendered plugins/redmine_pretend/app/views/user/_unpretend.html.erb (951.5ms)
Completed 500 Internal Server Error in 1099.7ms

ActionView::Template::Error (undefined local variable or method `real_user' for #<#<Class:0x007f3cd54a3710>:0x007f3cd4e20c08>):
    1: <% if session[:real_user_id] %>
    2:   <div class="flash error">
    3:     <%= l(:pretend_message) %> <%= real_user %>
    4:     <%= link_to l(:button_unpretend), unpretend_path, :class => 'icon', :method => :post %>
    5:   </div>
    6: <% end %>
  lib/redmine/hook.rb:111:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/layouts/base.html.erb:15:in `_app_views_layouts_base_html_erb___1453161293021956495_60462860'
  app/controllers/users_controller.rb:76:in `block (2 levels) in show'
  app/controllers/users_controller.rb:75:in `show`

**Comment by batizhevsky** [comment]
Sorry, forget add the method to helpers
