### ISSUE TITLE
Internal server error 500

### ISSUE THREAD

**Issue by simonefratini** [batizhevsky/redmine_pretend#20]
Hello 
I have some problem with your plugin in my installation, when I try to pretend to be an other user

Thanks in advance for your help.

redmine_pretend 
commit 9da2ad3cbd9fec53cb7645e7cc3762d7e383e64b

Environment:
  Redmine version                3.1.2.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  progressive_projects_list      3.0.1
  redmine_agile                  1.4.1
  redmine_banner                 0.1.1
  redmine_base_deface            0.0.1
  redmine_category_tree          0.0.6
  redmine_checklists             3.1.3
  redmine_last_updated_by_column 0.3.0
  redmine_latex_mathjax_macro    0.3.0
  redmine_maintenance_mode       2.0.1
  redmine_pretend                2.0.1
  redmine_silencer               0.4.1
  scrum                          0.14.0

> Log (with some xxx or yyy to offuscate real names, link and ip )

Started POST "/admin/pretend_to/182" for 10.21.xx.xxx at 2016-07-04 10:16:28 +0200
Processing by ApplicationController#pretend_to as HTML
  Parameters: {"authenticity_token"=>"ZY2sYRs6aJEHmOcXnfjRajx8EU2obqTqDDssfPLiYrFObwtXsvZBEFZOuMhgaoP2ELImm+cbqJ2oAR4yDoxxhg==", "id"=>"182"}
  Current user: xxxx.xxx (id=26)
xxxxx is pretend as yyyy 
Redirected to http://xxxx/users/182
Completed 302 Found in 33ms (ActiveRecord: 1.8ms)
Started GET "/users/182" for 10.21.xx.xxx at 2016-07-04 10:16:28 +0200
Processing by UsersController#show as HTML
  Parameters: {"id"=>"182"}
  Current user: yyy (id=182)
  Rendered plugins/redmine_pretend/app/views/user/_pretend_to.html.erb (3.3ms)
  Rendered users/show.html.erb within layouts/base (83.1ms)
  Rendered plugins/scrum/app/views/scrum_hooks/_head.html.erb (2.0ms)
  Rendered plugins/redmine_pretend/app/views/user/_unpretend.html.erb (62.3ms)
Completed 500 Internal Server Error in 415ms (ActiveRecord: 34.6ms)

ActionView::Template::Error (undefined local variable or method `real_user' for #<#<Class:0x007fc93d9c2260>:0x007fc93e067020>):
    1: <% if session[:real_user_id] %>
    2:   <div class="flash error">
    3:     <%= l(:pretend_message) %> <%= real_user %>
    4:     <%= link_to l(:button_unpretend), unpretend_path, :class => 'icon', :method => :post %>
    5:   </div>
    6: <% end %>
  lib/redmine/hook.rb:119:in `block (2 levels) in render_on'
  lib/redmine/hook.rb:117:in `map'
  lib/redmine/hook.rb:117:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:167:in `call_hook'
  app/views/layouts/base.html.erb:16:in `_c954dc4374302dd25d7c8d2353973fee'
  app/controllers/users_controller.rb:77:in `block (2 levels) in show'
  app/controllers/users_controller.rb:73:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by batizhevsky** [comment]
Are you use the latest revision? I fixed the bug few days ago

**Comment by simonefratini** [comment]
Yes I use the latest revision (commit 9da2ad3cbd9fec53cb7645e7cc3762d7e383e64b)

Maybe is there some wrong in my settings?

**Comment by batizhevsky** [comment]
No, I don't think that it on your side. I'll try in production mode, maybe something not loading in the proper way.

**Comment by simonefratini** [comment]
Solved now 
Done somethings on OS, but I don't know what trigger the solution

maybe "autoclean and upgrade ubuntu OS and restart " 

same redmine configuration

Environment:
  Redmine version                3.1.2.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  progressive_projects_list      3.0.1
  redmine_agile                  1.4.1
  redmine_banner                 0.1.1
  redmine_base_deface            0.0.1
  redmine_category_tree          0.0.6
  redmine_checklists             3.1.3
  redmine_last_updated_by_column 0.3.0
  redmine_latex_mathjax_macro    0.3.0
  redmine_maintenance_mode       2.0.1
  redmine_pretend                2.0.1
  redmine_silencer               0.4.1
  scrum                          0.14.0
